### ISSUE TITLE
Version 7.0 or newer does not work on Django 1.11 or older

### ISSUE THREAD

**Issue by hmpf** [applegrew/django-select2#537]
**Describe the bug**
Attempting to use version 7.0 or newer's Select2Widget leads to an exception on Django 1.11 or older. That 7.x does not support Django 1.11 is not documented sensibly.

**Exception & Traceback**

```
File "CENSORED1/widgets.py", line 4, in <module>
    from django_select2.forms import Select2Widget
File "CENSORED2/python3.7/site-packages/django_select2/forms.py", line 53, in <module>
    from django.contrib.admin.widgets import SELECT2_TRANSLATIONS
ImportError: cannot import name 'SELECT2_TRANSLATIONS' from 'django.contrib.admin.widgets' (CENSORED1/python3.7/site-packages/django/contrib/admin/widgets.py)
```
**Code Snippet**

Given Django 1.11, `python manage.py shell`:

```
import Select2Widget
```

**To Reproduce**
1. Import `Select2Widget` in a project that's made for Django 1.11.
2. See error

**Expected behavior**
No error.

**Comment by hmpf** [comment]
Workaround: lock the version of django-select2 to 6.3.1 on projects still on Django 1.11.

Correct fix: document what versions of Django are supported elsewhere than just the commits/changelog. For instance in the README.rst, or setup.py, or requirements.txt.

**Comment by codingjoe** [comment]
Hi @hmpf,

Version 7 (breaking change) links Django>=2.0 explicitly as a dependency. So yes, it does not work with Django 1.11 and no, that does not need to be documented IMHO, since pip should warn you about the version conflict.

Best
-Joe
