### ISSUE TITLE
Support for Python 3.4.3

### ISSUE THREAD

**Issue by davidetruffo** [applegrew/django-select2#151]
Hi!

i pip-installed Django-Select2-Py3 in my virtualenv, and it was working fine (on python 3.4.2), until i upgraded to python 3.4.3. Now i get this error:
````
...Downloading Django-Select2-Py3-4.2.1.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/Users/davidetruffo/Projects/venvs/mentor/build/Django-Select2-Py3/setup.py) egg_info for package Django-Select2-Py3
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/davidetruffo/Projects/venvs/mentor/build/Django-Select2-Py3/setup.py", line 166, in <module>
        long_description=read("README.md").decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/davidetruffo/Projects/venvs/mentor/build/Django-Select2-Py3/setup.py", line 166, in <module>

    long_description=read("README.md").decode('utf-8'),

AttributeError: 'str' object has no attribute 'decode'
````

**Comment by jonasrogert** [comment]
A sollution we found was to add the mode 'rb' to codecs.open, not sure if thats the correct solution but it seems to work on both 2.7 and 3.4.2 and 3.4.3.

I will create a pull request if that helps.

**Comment by codingjoe** [comment]
@jonasrogert can you create a PR?

**Comment by jonasrogert** [comment]
Pull request created. PR #152

**Comment by codingjoe** [comment]
Fixed in b077790

**Comment by jedie** [comment]
same error, here... No updated PyPi release available, yet?!?

**Comment by codingjoe** [comment]
@jedie nope, It's not pushed to pypi. Please use the current master.

**Comment by plitzenberger** [comment]
are you going to release this one of these days?

**Comment by applegrew** [comment]
@codingjoe Let me know when you feel good about the code. I can then push it to pypi.
