### ISSUE TITLE
Import Error: cannot import name '__ENABLE_MULTI_PROCESS_SUPPORT'

### ISSUE THREAD

**Issue by shamanis** [applegrew/django-select2#271]
Version: Django-Select2-Py3==4.2.1, Django==1.9.5

manage.py migrate retrun this:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/models/__init__.py", line 6, in <module>
    from .normdoc import NormDoc
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/models/normdoc.py", line 6, in <module>
    from fias.fields import UUIDField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/forms.py", line 6, in <module>
    from django_select2.fields import HeavyModelSelect2ChoiceField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/fields.py", line 87, in <module>
    from .widgets import Select2Widget, Select2MultipleWidget,\
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/widgets.py", line 7, in <module>
    from . import util
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/util.py", line 195, in <module>
    from . import __ENABLE_MULTI_PROCESS_SUPPORT as ENABLE_MULTI_PROCESS_SUPPORT, \
ImportError: cannot import name '__ENABLE_MULTI_PROCESS_SUPPORT'
```

**Comment by codingjoe** [comment]
Hi @shamanis
I'm sorry but django-select2 v4.x is no longer supported.
I'd like to encourage you to switch to Version 5.

Cheers,
Joe

**Comment by shamanis** [comment]
Where to get the version 5 Django-select2-Py3???
In PyPI latest available version is 4.2.1

**Comment by codingjoe** [comment]
```shell
pip install Django-Select2>=5.0.0
```
There isn't a py3 any longer. Version is written for py3 but also supports py2.7.
We have a [migration guide](https://github.com/applegrew/django-select2#upgrade-from-version-4) for people migrating from version 4 to 5.

Trust me, once you migrated, you never want to go back ;)

**Comment by JumpMan35** [comment]
Hello,
I try to use django_select2 by importing 'from django_select2.forms import Select2MultipleWidget'.
I'am working with pip 18.0 f packages/pip (python 3.6) and I have installed previously pip install django_select2.
But, I have an issue NameError: name 'ModelMultipleChoiceField' is not defined
It's seem that ModelMultipleChoiceField is not existing !
Any idea?
Thanks

**Comment by codingjoe** [comment]
Hi @JumpMan35 
thanks for reachng out. `ModelMultipleChoiceField` was removed in version 4 (we are at version 6.3.1 now). Please migrate to `ModelSelect2MultipleWidget `. 
Best
-Joe
